### ISSUE TITLE
拉进放大功能有待提升

### ISSUE THREAD

**Issue by zouzoutingtingiOS** [huangkunhe/RHScan#2]
你好 最近我找了一个二维码远距离扫描，发现你写的RHScan很不错，功能全部都实现了 但是唯一的拉进放大功能还是有瑕疵，支付宝有拉进放大的动画。

**Comment by huangkunhe** [comment]
1.0.2版本简单处理下放大动画效果，如果有好的建议和方案希望告知，谢谢~~

**Comment by huangkunhe** [comment]
1.0.2版本简单处理下放大动画效果，如果有好的建议和方案希望告知，有好的解决方案可以直接更新上传，共同维护，谢谢~~

**Comment by heysunnyboy** [comment]
微信扫描的功能在远处的时候才会有拉进动画，我发现你在远处的时候经常扫不到，另外距离二维码进的时候是不应该去有这个拉进动画的，然后感觉好诧异，应该是距离的远的时候才有这个动画
